[[plugins]]

  package = "netlify-plugin-flutter"

   [plugins.inputs]
    channel = "stable"

[build]

command = "touch .env && echo "BASE_URL=$BASE_URL" > .env && flutter build web --release"
publish = "build/web"